### ISSUE TITLE
BUG: Inplace not supported

### ISSUE THREAD

**Issue by larsoner** [SSLcom/actions-codesigner#1]
According to the docs, omitting `output_path` should make the tool operate inplace. However, when I try this, I get a build that "succeeds" but does not modify the binary:

https://github.com/mne-tools/mne-installers/actions/runs/3161136522/jobs/5146607163

Looking at the `EV-code sign installer (Windows)` step you'll see:
```
Run CodeSigner
  Running ESigner.com CodeSign Action ====>
  java.util.NoSuchElementException: No line found
  	at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
  	at com.ssl.code.signing.tool.commands.SignCommand.run(SignCommand.java:143)
  	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
  	at picocli.CommandLine.access$1300(CommandLine.java:145)
  	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
  	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
  	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
  	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
  	at picocli.CommandLine.execute(CommandLine.java:2078)
  	at com.ssl.code.signing.tool.CodeSignTool.main(CodeSignTool.java:35)
  Warn: '-output_directory' parameter is not set. The output signed file will replace the original file. Do you still want to continue [y/n]? 
```
which looks suspiciously like a `stdin` failure, but I could be wrong. And then in the next step I compare the hashes before and after and they are equal:
```
Old hash:
a81816db62c56d297217f863d7de9b164756e1efd110a625c7b38191b0b93b41 *MNE-Python-1.1.1_0-Windows.exe
New hash:
a81816db62c56d297217f863d7de9b164756e1efd110a625c7b38191b0b93b41  MNE-Python-1.1.1_0-Windows.exe
```

When I change the action to have a non-empty `output_path`, the output is reasonable:

https://github.com/mne-tools/mne-installers/actions/runs/3161464651/jobs/5147286622

```
 Running ESigner.com CodeSign Action ====>
  
  Code signed successfully: /github/workspace/signed/MNE-Python-1.1.1_0-Windows.exe
```

And the hashes do change:

```
Old hash:
64dd1e617805c0feb0ea35f0c2aa3a69a4af76cb6d4135328f3757e1730ec2fe *MNE-Python-1.1.1_0-Windows.exe
New hash:
e6d958683b6686df60b83dbaa5966a55b2e843ded5460cc156634a3f721809a8  MNE-Python-1.1.1_0-Windows.exe
```

So I think there is a bug with the Java inplace operation. Maybe a new command-line `-accept` could be added in Java that avoids this prompt (equivalent to accepting with "yes"), and then this could be passed inside this action when `output_path` is empty...?

**Comment by bayrakmustafa** [comment]
@larsoner We've reworked the codesigner github action for use on windows and macos runners. We created the github action at this address https://github.com/SSLcom/esigner-codesign. 

In the newly prepared github action, we added the 'override' parameter. If the 'override' parameter is set to true when the 'output_path' parameter is not sent, the signed file will overwrite the input file. Any chance to test it with the new github action?

**Comment by larsoner** [comment]
In [this branch](https://github.com/mne-tools/mne-installers/actions/runs/4599613148/jobs/8125846040) it looks like it works!
```
Code signed successfully: /home/runner/work/mne-installers/mne-installers/MNE-Python-1.3.1_0-Windows.exe
6s
Run shopt -s nullglob  # Fail if the following pattern yields no results
Finding matches
Extracting fname
Found name: MNE-Python-1.3.1_0-Windows.exe
Want name:  MNE-Python-1.3.1_0-Windows.exe
Old hash:
6a124a552258813c768b24ca5d0a17332802331106e168da5ce8604af7d28661 *MNE-Python-1.3.1_0-Windows.exe
New hash:
030bb73b663073620e78f4f8bec5765c0b58ef074278e9896f15e7da26390e99  MNE-Python-1.3.1_0-Windows.exe
```

**Comment by bayrakmustafa** [comment]
@larsoner Great :) I'm closing the issue. If you have a problem about new github action. You can create an issue at https://github.com/SSLcom/esigner-codesign
