### ISSUE TITLE
Action does not work for Windows runners

### ISSUE THREAD

**Issue by octopus-russell** [SSLcom/actions-codesigner#2]
Running the action on a Windows runner gives the following error

`Error: Container action is only supported on Linux`

It seems odd not to support Windows as the CodeSignTool tool is advertised as multi-platform

**Comment by bayrakmustafa** [comment]
@octopus-russell Container-based github actions only work on linux runners. For this, we prepared a new github action with typescript. Could you please test the github action at https://github.com/SSLcom/esigner-codesign on windows runner?

**Comment by bayrakmustafa** [comment]
@octopus-russell @butteff

**Comment by butteff** [comment]
Hello, sorry, I work for another project, but it looks like an API project, which is running on Linux as I know.
