### ISSUE TITLE
Action creates logs as root

### ISSUE THREAD

**Issue by johnheroy** [SSLcom/actions-codesigner#7]
This github action creates logs as root which introduces a new requirement to clean up these logs as root in our action definition - this wasn't always the behavior of this action - is it possible for the codesign tool to please not to do this?

```
john@box:~/path/to/workdir$ ls -l logs
-rw-r--r-- 1 root root 3128 Mar 15 19:15 code_signing_tool.log
```

**Comment by bayrakmustafa** [comment]
@johnheroy You can use https://github.com/SSLcom/esigner-codesign project. https://github.com/SSLcom/actions-codesigner is deprecated.
